version: '3.8'

services:
  redis:
    image: "redis:alpine"
    container_name: redis
    networks:
      - mongodb-network
    ports:
      - 6379:6379

  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    networks:
      - mongodb-network
    ports:
      - 27017:27017

  mongov2:
    image: mongo
    container_name: mongodbv2
    restart: always
    networks:
      - mongodb-network
    ports:
      - 27018:27017

  mongo-express:
    image: mongo-express
    container_name: mongoexpress
    depends_on:
      - mongo
    restart: always
    networks:
      - mongodb-network
    ports:
      - 9090:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    networks:
      - mongodb-network
    ports:
      - 5672:5672
      - 15672:15672
      - 1883:1883
    environment:
      - RABBITMQ_MQTT_DEFAULT_USER=guest
      - RABBITMQ_MQTT_DEFAULT_PASS=guest
    command: >
      sh -c "rabbitmq-plugins enable rabbitmq_mqtt && rabbitmq-server"
    restart: always

networks:
  mongodb-network:
    driver: bridge
