version: '3.1'

services:
  
  redis:
    image: "redis:alpine"
    container_name: redis
    networks:
      - mongodb-network
    ports:
      - 6379:6379
  
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    networks:
      - mongodb-network
    ports:
      - 27017:27017
      
  mongo-express:
    image: mongo-express
    container_name: mongoexpress
    depends_on:
      - mongo
    restart: always
    networks:
      - mongodb-network
    ports:
      - 9090:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    networks:
      - mongodb-network
    ports:
      - 5672:5672
      - 15672:15672
      
networks:
  mongodb-network:
    driver: bridge